Schoology.App.Attendance/Controllers/GlobalController.cs
using Newtonsoft.Json;
using Schoology.Api.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Schoology.Api.Entities.Models;
using System.Configuration;
using Schoology.App.Attendance.Models;
using System.Net;
using RazorPDF;

namespace Schoology.App.Attendance.Controllers
{
    public class GlobalController : Controller
    {
        private static List<GradingPeriod> _gradingPeriodList = new List<GradingPeriod>();
        private static List<Course> _totalCourseList { get; set; }
        private static List<Course> _filterCourseList { get; set; }

        /// <summary>
        /// Loads the Courses and Sections for both Global Attendance by All Day and by Time.
        /// </summary>
        /// <param name="searchString">Find by Name SearchString to filter the Course Listing.</param>
        /// <returns></returns>
///        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        private ActionResult LoadCourseSections(string searchString)
        {
            // Create the list to hold the users.
            List<Course> filterList = new List<Course>();

            // Initialize the Grid.MVC searching, sorting and search string.
            GridMVCModel gridMVCModel = new GridMVCModel();

            ViewBag.gridPage = 1;
            ViewBag.gridFilter = "";
            ViewBag.gridColumn = "";
            ViewBag.gridDir = 0;
            ViewBag.SearchString = "";

            // Proformance Issues
            // We only want to load data when we hit this page.
            // If the post-back for grid paging and filtering, do not reload the data.

            // If no query strings, load the data once and store in static variable
            if (Request.QueryString.Count == 0)
            {
                // Get the users from Schoology
                _totalCourseList = CourseService.Instance.GetCoursesWithSectionsJsonFile();

                // Set the Grid.MVC grid-page to 1 because if we go to the details page and return it will reload all the data.
                ViewBag.gridPage = 1;

            }
            else
            {
                // Set the view bag variables to be passed to the details page so we can return back to where we started from.
                // Grid Page
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-page"]))
                {
                    ViewBag.gridPage = int.Parse(Request.QueryString["grid-page"]);
                }

                // Grid Filter
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-filter"]))
                {
                    ViewBag.gridFilter = Request.QueryString["grid-filter"];
                }

                // Grid Sort Direction
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-dir"]))
                {
                    ViewBag.gridDir = Request.QueryString["grid-dir"];
                }

                // Grid Sort Column
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-column"]))
                {
                    ViewBag.gridColumn = Request.QueryString["grid-column"];
                }

                // Filter Textbox
                if (!string.IsNullOrWhiteSpace(Request.QueryString["SearchString"]))
                {
                    ViewBag.SearchString = Request.QueryString["SearchString"];
                }

            }

            // Filter the list by FirstName or LastName.
            if (!string.IsNullOrEmpty(searchString))
            {
                ViewBag.SearchString = searchString;

                // Now that we have all the users, check to see if we need to filter them.
                if (!string.IsNullOrEmpty(searchString))
                {
                    _filterCourseList = _totalCourseList.Where(s =>

                        s.title.ToLower().Contains(searchString.ToLower()) ||
                        s.course_code.ToLower().Contains(searchString.ToLower()) ||
                        s.section.Any(c => c.section_title.ToLower().Contains(searchString.ToLower()))

                        ).ToList();

                }
            }
            else
            {
                _filterCourseList = _totalCourseList;
            }

            gridMVCModel.GridPage = Convert.ToInt32(ViewBag.gridPage);
            gridMVCModel.GridFilter = ViewBag.gridFilter;
            gridMVCModel.GridColumn = ViewBag.gridColumn;
            gridMVCModel.GridDir = Convert.ToInt32(ViewBag.gridDir);
            gridMVCModel.SearchString = ViewBag.searchString;

            Session["gridMVCModel"] = gridMVCModel;

            return View(_filterCourseList);
        }

        /// <summary>
        /// Loads the courses and section for Global Attendance by All Day.
        /// </summary>
        /// <param name="searchString">Find by Name SearchString to filter the Course Listing.</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult AllDayIndex(string searchString)
        {
            return LoadCourseSections(searchString);
        }

        /// <summary>
        /// Loads the courses and sections for Global Attendance by Time.
        /// </summary>
        /// <param name="searchString">Find by Name SearchString to filter the Course Listing.</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult TimeIndex(string searchString)
        {
            return LoadCourseSections(searchString);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="currentDate"></param>
        /// <returns></returns>
        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult AllDayAttendance(long id, DateTime currentDate)
        {
            SetGridMVCViewBag();

            //string sectionValidationSummary = SectionService.Instance.ValidateSection(id);
            //if(!string.IsNullOrEmpty(sectionValidationSummary))
            //    return RedirectToAction("Error", new { errorMessage = sectionValidationSummary, actionName = "AllDayIndex" });

            // We only want to display the class attendance on the days that the class is scheduled.
            // So we need to find out when the class is scheduled based on days and set the current date in the
            // datepicker to the closest day. The datepicker will take care of the rest by disabling the days
            // that the class does not meet.

            // The currentDate is set the the current date when this page is first accessed.
            // The user can change the date and will post back to this method.

            // 0 = sunday, 1 = monday, 2 = tuesday, 3 = wednesday, 4 = thrusday, 5 = friday, 6 = saturday
            // Disable the JQuery Datepicker days the class is not scheduled on.
            string daysToDisable = "0,6";
            ViewBag.daysToDisable = daysToDisable;

            // Check the date to when the class meets. If the date is on a disabled date, then find the next date the class is schedule on.
            // This will only happen the first time this page is accessed.
            // 0 = sunday, 1 = monday, 2 = tuesday, 3 = wednesday, 4 = thrusday, 5 = friday, 6 = saturday

            int dayOfWeekNumber = (int)currentDate.DayOfWeek;
            int nextDayOfWeekNumber;
            //DateTime date = currentDate;

            if (daysToDisable.Contains(dayOfWeekNumber.ToString()))
            {
                nextDayOfWeekNumber = (dayOfWeekNumber == 5) ? dayOfWeekNumber = 1 : dayOfWeekNumber++;
                currentDate = ClassSchedule.GetNextDateForDay(DateTime.Now, (DayOfWeek)Enum.Parse(typeof(DayOfWeek), nextDayOfWeekNumber.ToString()));
            }


            string searchDate = currentDate.ToString("yyyy-MM-dd");

            ViewBag.searchDate = searchDate;

            ViewBag.AttendanceCode = AttendanceService.Instance.GetAttendanceCodes();



            //if (id == null)
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}

            Course course = _totalCourseList.Single(p => p.section.Any(x => x.id == id));

            Section section = course.section.Single(x => x.id == id);

            //User user = _totalList.Where(x => x.id == id);
            //Course course = _totalCourseList.Single(x => x.id == id);

            //List<Enrollment> enrollmentList = EnrollmentService.Instance.GetSectionEnrollments(section.id, false, false);
            // Json File Call
            // For increase proformance
            List<Enrollment> enrollmentList = EnrollmentService.Instance.GetSectionEnrollmentsJsonFile(section.id, true);

            // Only select the active students and not the teacher.
            // The current status of the enrollment.
            //  1: Active
            //  2: Expired (i.e. past course)
            //  3: Invite pending
            //  4: Request Pending
            //  5: Archived (Course specific status members can be placed in before being fully unenrolled)

            // Get the teachers. Used for roster printing.
            long superAdminId = Convert.ToInt64(ConfigurationManager.AppSettings["superAdmin"]);
            section.teachers = enrollmentList.Where(x => x.admin == 1 && x.status == "1" && x.uid != superAdminId).ToList();

            enrollmentList = enrollmentList.Where(x => x.admin != 1 && x.status == "1").ToList();

            // Set the students for the section.
            section.enrollments = enrollmentList;


            // Create one attendance record a initials for the form.
            // Based on the dates, if there is more than one we will duplicate the attendance record for the other dates.
            foreach (Enrollment enrollment in section.enrollments)

Schoology.App.Attendance/Views/Global/AllDayAttendance.cshtml
@model Schoology.Api.Entities.Models.Section

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />
@*<link rel="Stylesheet" href="~/Content/themes/BILTZER/jquery-ui.css" />*@

@{
    ViewBag.Title = "Global Attendance by All Day";
}

<h3>@ViewBag.Title</h3>

<div class="row">

    <div id="sectioninfo" class="col-md-3">

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.course_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.course_code):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_code)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.section_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.section_title)
            </dd>

            
                @if (Model.course_code.ToLower() == "ath 100")
                {
                    <dt>
                        Coach:
                    </dt>
                }
                else
                    {
                    <dt>
                        Faculty:
                    </dt>
                }

            <dd>
                @if (Model.teachers.Count > 0)
                {
                    @Html.DisplayFor(model => model.teachers[0].name_display)
                }
                else
                {
                    <p>n/a</p>
                }
            </dd>
        </dl>
    </div>
    <p>
        <b>
            @Html.ActionLink("Print Roster", "RosterPDF", "Global", new { id = @Model.id, date = @ViewBag.searchDate }, new { target = "_blank" })
        </b>
    </p>
</div>

<p>
    @Html.ActionLink("Back to List", "AllDayIndex",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })
</p>


@using (Html.BeginForm("AllDayAttendance", "Global", FormMethod.Post, new { id = "sectionform" }))
{

    <div class="editor-field">
        <label for="date">Start Date:</label>

        @Html.TextBox("startdate")

        &nbsp;&nbsp;<label for="date">End Date:</label>

        @Html.TextBox("enddate")
    </div>
    
    <br />

    @Html.DropDownList("SelectAllAttendanceCodes",

                  new SelectList(ViewBag.AttendanceCode, "Key", "Value"),
                                              // Text for the first 'default' option
                                              "- Select Attendance Code -"
                                             )

    <label>&nbsp;&nbsp;Comment:</label> @Html.TextBox("SelectAllComment", "", new { style="width:300px"})

    <br />
    <br />

    <table id='myTable' class="table">

        <tr>
            <th>@Html.CheckBox("checkall")</th>
            <th>Student Name</th>
            <th width="70%"></th>
        </tr>

        <tbody>

            @for (int i = 0; i < Model.enrollments.Count; ++i)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="sid" value="@Model.enrollments[i].attendances[0].enrollment_id" class="sid" />
                    </td>
                    <td>
                        <img height="42" width="50" src=@Model.enrollments[i].picture_url /> @Html.DisplayFor(m => m.enrollments[i].name_last), @Html.DisplayFor(m => m.enrollments[i].name_first) <a href=@Html.Raw(@String.Format(@"'https://www.schoology.com/course/{0}/reports/{1}/attendance'", Model.id, Model.enrollments[i].uid)) target="_blank"><img src="~/Images/stats.png" align="top" /></a>
                        
                        @Html.HiddenFor(m => @Model.enrollments[i].id)
                        @Html.HiddenFor(m => @Model.enrollments[i].uid)
                        @Html.HiddenFor(m => @Model.enrollments[i].name_first)
                        @Html.HiddenFor(m => @Model.enrollments[i].name_last)

                        @Html.HiddenFor(m => Model.enrollments[i].attendances[0].enrollment_id)
                        @Html.HiddenFor(m => Model.enrollments[i].attendances[0].date)
                        @Html.HiddenFor(m => Model.enrollments[i].attendances[0].status)
                        @Html.HiddenFor(m => Model.enrollments[i].attendances[0].comment)

                    </td>
                    <td width="70%"></td>
                </tr>
            }

        </tbody>

    </table>

    <div class="form-group">
        @*<div class="col-md-offset-2 col-md-10">*@
        <div>
            <input type="submit" value="Save Changes" id="save" />
        </div>
    </div>
}

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |*@
    @Html.ActionLink("Back to List", "AllDayIndex",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })
</p>


<script type="text/javascript">

    // unblock when ajax activity stops 
    $(document).ajaxStop($.unblockUI);

    $(function () {

        //var daysToDisable = [0, 3, 6];

        // 0 = sunday, 1 = monday, 2 = tuesday, 3 = wednesday, 4 = thrusday, 5 = friday, 6 = saturday

        var daysToDisable = JSON.parse("[" + '@ViewBag.daysToDisable' + "]");

        $('#startdate').datepicker({
            dateFormat: "yy-mm-dd",
            changeMonth: true,
            changeYear: true,
            showOn: 'both',
            buttonImage: "../../images/attendance.png",
            buttonImageOnly: true,
            autoSize: true,
            onSelect: function (date) {
                var date2 = $('#startdate').datepicker('getDate');
                date2.setDate(date2.getDate());
                $('#enddate').datepicker('setDate', date2);
                //sets minDate to dt1 date + 1
                $('#enddate').datepicker('option', 'minDate', date2);

            },

            beforeShowDay: disableSpecificWeekDays

        }).datepicker("setDate", '@ViewBag.searchDate');

        $('#enddate').datepicker({
            dateFormat: "yy-mm-dd",
            changeMonth: true,
            changeYear: true,
            showOn: 'both',
            buttonImage: "../../images/attendance.png",
            buttonImageOnly: true,
            autoSize: true,
            onClose: function () {
                var dt1 = $('#startdate').datepicker('getDate');

                var dt2 = $('#enddate').datepicker('getDate');
                if (dt2 <= dt1) {
                    var minDate = $('#enddate').datepicker('option', 'minDate');
                    $('#enddate').datepicker('setDate', minDate);
                }
            },

            beforeShowDay: disableSpecificWeekDays

        });

        function disableSpecificWeekDays(date) {
            var day = date.getDay();
            for (i = 0; i < daysToDisable.length; i++) {
                if ($.inArray(day, daysToDisable) != -1) {
                    return [false];
                }
            }
            return [true];
        }

        // Fires the onSelect event when page loads.
        $('.ui-datepicker-current-day').click();

        //$('#save').click(function () {
        //    $.blockUI({ message: '<h1><img src="../../images/busy.gif" /> Saving Data...</h1>' });
        //});

        $('#save').click(function () {

            var ischeckallChecked = $('#checkall').is(":checked")
            if (ischeckallChecked) {

                if ($('#SelectAllAttendanceCodes').val() == false) {

                    //alert("Please select an attendance code.");
                    //$.blockUI({ message: '<h1>Attendance Code is required.</h1>' });
                    ValidationDialog("Attendance Code is required.");
                    //$("#dialog").dialog("open");
                    return false; // will not refresh the page.
                }
            }


            $.blockUI({
                message: '<h4>Please Wait...</h4>',

                css: {
                    border: 'none',
                    padding: '15px',
                    backgroundColor: '#000',
                    '-webkit-border-radius': '10px',
                    '-moz-border-radius': '10px',
                    opacity: .5,
                    color: '#fff'
                }
            });
        });



        function ValidationDialog(message) {
            $("#dialog").html(message);

            // Define the Dialog and its properties.
            $("#dialog").dialog({
                resizable: false,
                modal: true,
                title: "Attendance by Time",
                height: 150,
                width: 300
            });
        }

    });

</script>


<script>
    $("document").ready(function () {

        $('#myTable td input:checkbox').prop('disabled', true);

        $('#myTable th input:checkbox').click(
            function () {
                $('input:checkbox').prop('checked', this.checked);
            }
        );

        $('#myTable tr input:checkbox').click(
            function () {
                var checkedCount = $('#myTable td input:checkbox:checked').length;
                //alert(checkedCount);
                var totalCount = $('#myTable td input:checkbox').length;
                //alert(totalCount);
                var selectAllChecked = $('#myTable th input:checkbox').prop('checked')
                //alert(selectAllChecked);

                $('#myTable th input:checkbox').prop('checked', selectAllChecked && checkedCount > 0);
                $('#myTable td input:checkbox').prop('disabled', !selectAllChecked);

                if (!selectAllChecked) {
                    $('#myTable th input:checkbox').focus();
                    $('#myTable td input:checkbox').prop('checked', false);

                }

            }
        );

    });
</script>

<div id="dialog">

</div>

Schoology.App.Attendance/Views/Global/AllDayIndex.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.Course>

@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Global Attendance by All Day";
}

<h3>@ViewBag.Title</h3>

<meta name="viewport" content="width=device-width" />

<script>

        $(function () {

            $("#Clear").on("click", function (event) {
                $("#SearchString").val("");
            });

            // Grid row selected event
            //pageGrids.courseGrid.onRowSelect(function (e) {
            //    alert(e.row.uid);
            //});

        });

</script>

@using (Html.BeginForm("AllDayIndex", "Global", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

@Html.Grid(Model).Named("courseGrid").Columns(columns =>
{
    /* Adding "OrderID" column: */
    columns.Add(model => model.title)
            .Titled("Title")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(200);

    columns.Add(model => model.course_code)
        .Titled("Course Code")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(30);

    columns.Add()
        .Titled("Sections")
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(200)
        .RenderValueAs(d =>
            @<b>
                @foreach (var a in d.section)
                {
                    @Html.ActionLink(@a.section_title, "AllDayAttendance", new { id = a.id, currentDate = DateTime.Now })

                    <br />
                }

            </b>

        );

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(100)
        .RenderValueAs(d =>
            @<b>

            </b>);


}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Global/Index.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.Course>

@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Course Listing";
}

<h2>@ViewBag.Title</h2>


<meta name="viewport" content="width=device-width" />

<script>

        $(function () {

            $("#Clear").on("click", function (event) {
                $("#SearchString").val("");
            });

            // Grid row selected event
            //pageGrids.courseGrid.onRowSelect(function (e) {
            //    alert(e.row.uid);
            //});

        });

</script>


@using (Html.BeginForm("Index", "Global", FormMethod.Get))
{
    @*<p>
            Select Grading Period: @Html.DropDownList("gradingPeriod")
            <input type="submit" value="Filter" />
        </p>*@

    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

@Html.Grid(Model).Named("courseGrid").Columns(columns =>
{


    /* Adding "OrderID" column: */
    columns.Add(model => model.title)
            .Titled("Title")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(200);

    columns.Add(model => model.course_code)
        .Titled("Course Code")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(30);

    columns.Add()
        .Titled("Sections")
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(200)
        .RenderValueAs(d =>
            @<b>
                @foreach (var a in d.section)
                {



                    @*@Html.ActionLink(@a.section_title, "Index", new RouteValueDictionary(
                        new { controller = "Section", id = a.id }))*@

                    @Html.ActionLink(@a.section_title, "Section", new { id = a.id, currentDate = DateTime.Now })

                    <br />
                }

            </b>

        );

    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(100)
    .RenderValueAs(d =>
        @<b>

        </b>);


}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Global/RosterPDF.cshtml
@model Schoology.Api.Entities.Models.Section
@{
    Layout = null;
}


@{
    ViewBag.Title = "Class Roster";
}

<style>
    table {
        border-collapse: separate;
        border-spacing: 0 5em;
    }
</style>


<center>
    <h2>Valor Christian High School</h2>


    <h3>Class Roster</h3>
</center>

<table>
    <tr>
        <td align="right">Date:&nbsp;</td>
        <td>@ViewBag.Date</td>
    </tr>
    <tr>
        <td align="right">Course Title:&nbsp;</td>
        <td>@Model.course_title</td>
    </tr>
    <tr>
        <td align="right">Course Code:&nbsp;</td>
        <td>@Model.course_code</td>
    </tr>
    <tr>
        <td align="right">Section Title:&nbsp;</td>
        <td>@Model.section_title</td>
    </tr>
    <tr>
        @if (Model.teachers.Count > 0)
        {
            <td align="right">Faculty:&nbsp;</td>
            <td>@Model.teachers[0].name_display</td>
        }
        else
        {
            <td align="right">Faculty:&nbsp;</td>
            <td>n/a</td>
        }
    </tr>
</table>

<br />
<hr />

<table id='myTable' class="table" align="center">

    <tr>
        <th>@Html.CheckBox("checkall")</th>
        <th>Student Name</th>
    </tr>

    <tbody>

        @for (int i = 0; i < Model.enrollments.Count; ++i)
        {
            <tr>
                <td align="right">
                    ________
                </td>
                <td>
                    @Html.DisplayFor(m => m.enrollments[i].name_last), @Html.DisplayFor(m => m.enrollments[i].name_first)


                </td>


            </tr>

        }


    </tbody>

</table>

Schoology.App.Attendance/Views/Global/TimeAttendance.cshtml
@model Schoology.Api.Entities.Models.Section

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />
@*<link rel="Stylesheet" href="~/Content/themes/BILTZER/jquery-ui.css" />*@

@{
    ViewBag.Title = "Global Attendance by Time";
}

<h3>@ViewBag.Title</h3>

<div class="row">

    <div id="sectioninfo" class="col-md-3">

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.course_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.course_code):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_code)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.section_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.section_title)
            </dd>

            @if (Model.course_code.ToLower() == "ath 100")
            {
                <dt>
                    Coach:
                </dt>
            }
            else
            {
                <dt>
                    Faculty:
                </dt>
            }

            <dd>
                @if (Model.teachers.Count > 0)
                {
                    @Html.DisplayFor(model => model.teachers[0].name_display)
                }
                else
                {
                    <p>n/a</p>
                }
            </dd>

        </dl>
    </div>
    <p>
        <b>
            @Html.ActionLink("Print Roster", "RosterPDF", "Global", new { id = @Model.id, date = @ViewBag.searchDate }, new { target = "_blank" })
        </b>
    </p>
</div>

@using (Html.BeginForm("TimeAttendance", "Global", FormMethod.Post, new { id = "sectionform" }))
{
    <div class="row">
        <div class="col-md-7">
            @Html.Partial("_TimeAttendanceGrid") @* configure grid in a partial view *@
        </div>
        <div class="col-md-5">
            <div id="schedule-content">
                <p class="muted">
                </p>
            </div>
        </div>

    </div>

}

Schoology.App.Attendance/Views/Global/TimeIndex.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.Course>

@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Global Attendance by Time";
}

<h3>@ViewBag.Title</h3>

<meta name="viewport" content="width=device-width" />

<script>

    $(function () {

        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row selected event
        //pageGrids.courseGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });

</script>

@using (Html.BeginForm("TimeIndex", "Global", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

@Html.Grid(Model).Named("courseGrid").Columns(columns =>
{
    /* Adding "OrderID" column: */
    columns.Add(model => model.title)
            .Titled("Title")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(200);

    columns.Add(model => model.course_code)
        .Titled("Course Code")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(30);

    columns.Add()
        .Titled("Sections")
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(200)
        .RenderValueAs(d =>
            @<b>
                @foreach (var a in d.section)
                {
                    @Html.ActionLink(@a.section_title, "TimeAttendance", new { id = a.id, currentDate = DateTime.Now })

                    <br />
                }

            </b>

        );

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(100)
        .RenderValueAs(d =>
            @<b>

            </b>);


}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Global/_Test.cshtml
@ViewBag.CalendarDate

<input type="checkbox" name="newSid" value="abc" class="newSid" />