Schoology.App.Attendance/Controllers/StudentController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Configuration;
using Schoology.Api.Service;
using Schoology.Api.Entities.Models;
using System.Net;
using Schoology.App.Attendance.Models;
using log4net;

namespace Schoology.App.Attendance.Controllers
{
    public class StudentController : Controller
    {

        // Log file
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        private static List<User> _totalUserList { get; set; }

        private List<User> LoadStudents(string searchString)
        {
            // Create the list to hold the users.
            List<User> filterUserList = new List<User>();

            // Initialize the Grid.MVC searching, sorting and search string.
            GridMVCModel gridMVCModel = new GridMVCModel();

            ViewBag.gridPage = 1;
            ViewBag.gridFilter = "";
            ViewBag.gridColumn = "";
            ViewBag.gridDir = 0;
            ViewBag.SearchString = "";

            // Proformance Issues
            // We only want to load data when we hit this page.
            // If the post-back for grid paging and filtering, do not reload the data.

            // If no query strings, load the data once and store in static variable
            if (Request.QueryString.Count == 0)
            {
                // Get the users from Schoology Json File instead of calling the Schoology API directly.
                _totalUserList = UserService.Instance.GetUsersJsonFile();

                // Set the Grid.MVC grid-page to 1 because if we go to the details page and return it will reload all the data.
                ViewBag.gridPage = 1;

            }
            else
            {
                // Set the view bag variables to be passed to the details page so we can return back to where we started from.
                // Grid Page
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-page"]))
                {
                    ViewBag.gridPage = int.Parse(Request.QueryString["grid-page"]);
                }

                // Grid Filter
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-filter"]))
                {
                    ViewBag.gridFilter = Request.QueryString["grid-filter"];
                }

                // Grid Sort Direction
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-dir"]))
                {
                    ViewBag.gridDir = Request.QueryString["grid-dir"];
                }

                // Grid Sort Column
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-column"]))
                {
                    ViewBag.gridColumn = Request.QueryString["grid-column"];
                }

                // Filter Textbox
                if (!string.IsNullOrWhiteSpace(Request.QueryString["SearchString"]))
                {
                    ViewBag.SearchString = Request.QueryString["SearchString"];
                }


            }

            // Filter the list by FirstName or LastName.
            if (!string.IsNullOrEmpty(searchString))
            {
                ViewBag.SearchString = searchString;

                // Now that we have all the users, check to see if we need to filter them.
                if (!string.IsNullOrEmpty(searchString))
                {
                    //filterUserList = _totalUserList.Where(s => s.name_last.ToLower().Contains(searchString.ToLower())
                    //    || s.name_first.ToLower().Contains(searchString.ToLower())).ToList();


                    // Temporary solution. Need to filter only student that are current students and have a StudentID. This needs to be done in UserService.cs
                    _totalUserList = _totalUserList.Where(s => !string.IsNullOrEmpty(s.name_title)).ToList();
                        

                    //foreach(User user in _totalUserList)
                    //{
                    //    if(string.IsNullOrEmpty(user.position))
                    //    {
                    //        User temp = user;

                    //    }
                    //}

                    filterUserList = _totalUserList.Where(s => s.name_last.ToLower().Contains(searchString.ToLower())
                        || s.name_first.ToLower().Contains(searchString.ToLower())
                        || s.name_title.ToLower().Contains(searchString.ToLower())).ToList();
                }
            }
            else
            {
                filterUserList = _totalUserList;
            }

            gridMVCModel.GridPage = Convert.ToInt32(ViewBag.gridPage);
            gridMVCModel.GridFilter = ViewBag.gridFilter;
            gridMVCModel.GridColumn = ViewBag.gridColumn;
            gridMVCModel.GridDir = Convert.ToInt32(ViewBag.gridDir);
            gridMVCModel.SearchString = ViewBag.searchString;

            Session["gridMVCModel"] = gridMVCModel;

            //List<Attendance> list = attendanceRoot.attendance.Where(x => x.date == "2015-06-03").ToList();

            return filterUserList;
        }

        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult StudentSchedulePDF(int id, string firstname, string lastname)
        {

            return Redirect("https://schoology.valorchristian.com/SchoologyAppSchedule/schedule/StudentSchedulePDF/6329?firstname=Rachel&lastname=Abraham"); // redirects to external url


            //return View(LoadStudents(searchString));
        }


        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult DayIndex(string searchString)
        {
            return View(LoadStudents(searchString));
        }

        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult ClassIndex(string searchString)
        {

            return View(LoadStudents(searchString));
        }

        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        public ActionResult DayAttendance(long id)
        {
            SetGridMVCViewBag();

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //User user = _totalList.Where(x => x.id == id);
            User user = _totalUserList.Single(x => x.id == id);

            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);

        }

        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        [HttpPost]
        public ActionResult DayAttendance(long id, string startdate, string enddate, List<StudentAttendanceByDayModel> list )
        {
            SetGridMVCViewBag();

            // loop through the selected dates
            foreach(StudentAttendanceByDayModel model in list)
            {
                int blackBaudCode = 0;
                int schoologyStatusCode = 0;

                if(model.Status > 0)
                {
                    StudentAttendanceByDayModel studentAttendance = new StudentAttendanceByDayModel();

                    studentAttendance.Date = model.Date;

                    // Separate the attendance code.
                    blackBaudCode = model.Status % 10;
                    schoologyStatusCode = model.Status / 10;

                    // Set the schoology attendance code (1, 2, 3, 4)
                    studentAttendance.Status = schoologyStatusCode;


                    // BUG: To fix the date problem.
                    if (studentAttendance.Status == 1)
                    {
                        if (string.IsNullOrEmpty(model.Comment))
                        {
                            studentAttendance.Comment = " "; // This because we don't want the record to show up the the students overall attendance summary.
                        }

                    }
                    else
                    {
                        // BUG: To fix the date problem.
                        if (string.IsNullOrEmpty(model.Comment))
                        {
                            model.Comment = " ";
                        }

                        studentAttendance.Comment = blackBaudCode.ToString() + model.Comment;
                    }

                    string returnValue = UserService.Instance.PutUserSectionsAttendanceJson(
                        id,
                        Convert.ToDateTime(studentAttendance.Date),
                        studentAttendance.Status,
                        studentAttendance.Comment
                    );

                }
            }

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = _totalUserList.Single(x => x.id == id);

            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);

        }

        private IEnumerable<DateTime> EachDay(DateTime from, DateTime thru)
        {
            for (var day = from.Date; day.Date <= thru.Date; day = day.AddDays(1))
                yield return day;
        }

        [Authorize(Roles = "Admin, School Admin, Front Desk")]
        [HttpPost]
        public ActionResult DayAttendanceGrid(string startDate, string endDate)
        {
            ViewBag.AttendanceCode = AttendanceService.Instance.GetAttendanceCodes();

            List<StudentAttendanceByDayModel> list = new List<StudentAttendanceByDayModel>();

            foreach (DateTime date in EachDay(Convert.ToDateTime(startDate), Convert.ToDateTime(endDate)))
            {
                StudentAttendanceByDayModel model = new StudentAttendanceByDayModel();

                model.Date = date.ToShortDateString();
                model.CycleDay = date.DayOfWeek.ToString();

Schoology.App.Attendance/Views/Student/Attendance.cshtml
@model Schoology.Api.Entities.Models.User



@*<link rel="stylesheet" href="~/Content/themes/base/core.css" />
    <link rel="stylesheet" href="~/Content/themes/base/datepicker.css" />
    <link rel="stylesheet" href="~/Content/themes/base/theme.css" />
    <script src="~/Scripts/jquery-2.1.4.js" type="text/javascript"></script>*@
    <script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>


<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />

@{
    ViewBag.Title = "Attendance";
}

<h2>@ViewBag.Title</h2>



<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name_last):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_last)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name_first):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name_first)
        </dd>



    </dl>
</div>

@{
    var dateSelected = Request.Form["attendancedate"];
    ViewBag.dateSelected = dateSelected;
    if (IsPost)
    {
        <text>
            You entered: <br />
            Date Selected: @dateSelected <br />

            Monday: @Request.Form["mondayhidden"];
        </text>
    }
}


@using (Html.BeginForm("Attendance", "Student", FormMethod.Post))
{

    
    
    
    <p>


        <div class="editor-field">
            <label for="date">Select a date:</label>
            @Html.JQueryUI().Datepicker("attendancedate").ShowOn(DatepickerShowOn.Button, "../../images/calendar.gif", "Select Date", true).ChangeYear(true).ChangeMonth(true)
        </div>



        <div>
            <label for="anotherDate">Select another date: </label>
            @(Html.JQueryUI().Datepicker("anotherDate").MinDate(DateTime.MinValue).ShowButtonPanel(true)
.ChangeYear(true).ChangeMonth(true).NumberOfMonths(1))
        </div>


        @*@Html.JQueryUI().Button("Search", ButtonElement.Button, ButtonType.Submit, null)*@


        <div class="editor-field">
            <label for="attendancedate">Select a date:</label>
            @Html.JQueryUI().Datepicker("AttendanceDate").Inline(true).AlternateField("#d","mm/dd/yyyy").ChangeYear(true).ChangeMonth(true).NumberOfMonths(1)
            

        </div>

        <input type="text" id="d" />

        <div id="z"></div>

        <div class="week-picker"></div>
        <br /><br />
        <label>Week :</label> <span id="startDate"></span> - <span id="endDate"></span>

        <label>Monday :</label> <span id="monday"></span>
        <label>Tuesday :</label> <span id="tuesday"></span>
        <label>Wednesday :</label> <span id="wednesday"></span>
        <label>Thursday :</label> <span id="thursday"></span>
        <label>Friday :</label> <span id="friday"></span>

        <input type="text" id="mondayhidden" value="abc">

    </p>


    
    <div class="form-horizontal">
        <h4>Student</h4>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-default" />
            </div>
        </div>
    </div>
    
}



<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |*@
    @Html.ActionLink("Back to List", "Index",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })


</p>


<script type="text/javascript">
    $(function () {
        var startDate;
        var endDate;
        var monday;
        var tuesday;
        var wednesday;
        var thursday;
        var friday;

        var selectCurrentWeek = function () {
            window.setTimeout(function () {
                $('.week-picker').find('.ui-datepicker-current-day a').addClass('ui-state-active')
            }, 1);
        }
       

        $('.week-picker').datepicker({
            changeYear: true,
            changeMonth: true,
            showOtherMonths: true,
            selectOtherMonths: true,
            onSelect: function (dateText, inst) {
                var date = $(this).datepicker('getDate');
                startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay());
                endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 6);
                var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;
                $('#startDate').text($.datepicker.formatDate(dateFormat, startDate, inst.settings));
                $('#endDate').text($.datepicker.formatDate(dateFormat, endDate, inst.settings));

                monday = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 1);
                tuesday = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 2);
                wednesday = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 3);
                thursday = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 4);
                friday = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 5);
                $('#monday').text($.datepicker.formatDate(dateFormat, monday, inst.settings));
                $('#tuesday').text($.datepicker.formatDate(dateFormat, tuesday, inst.settings));
                $('#wednesday').text($.datepicker.formatDate(dateFormat, wednesday, inst.settings));
                $('#thursday').text($.datepicker.formatDate(dateFormat, thursday, inst.settings));
                $('#friday').text($.datepicker.formatDate(dateFormat, friday, inst.settings));
   
                $('#mondayhidden').val($.datepicker.formatDate(dateFormat, monday, inst.settings));


                selectCurrentWeek();

                //alert("hi");
                //$.blockUI({ message: '<h1><img src="../../images/busy.gif" /> Just a moment...</h1>' });
                $.blockUI({ message: $('#domMessage') });
                $.ajax({
                    type: "post",
                    url: "/student/attendance",
                    data: "mondayhidden=" + date + "&monday=123",
                    success: function (data) {
                        //alert("success");
                        $("#tblAppts").html(data);
                        $.unblockUI();
                    },
                    error: function (xhr, status, error) {
                        $.unblockUI();
                        alert("error");
                    }
                });

            },

            beforeShowDay: function (date) {
                var cssClass = '';
                if (date >= startDate && date <= endDate)
                    cssClass = 'ui-datepicker-current-day';
                return [true, cssClass];
            },

            onChangeMonthYear: function (year, month, inst) {
                selectCurrentWeek();
            }
         
        });

        // Show current week on load
        //$(".ui-datepicker-current-day").click();


    });



</script>
<div id="domMessage" style="display:none;">
    <h1>We are processing your request.  Please be patient.</h1>
</div>

Schoology.App.Attendance/Views/Student/ClassAttendance.cshtml
@model Schoology.Api.Entities.Models.User

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />

@{
    ViewBag.Title = "Student Attendance By Class";
}

<h3>@ViewBag.Title</h3>

<div class="row">
    <div class="col-md-1">
        <img height="84" width="100" src=@Model.picture_url />
    </div>

    <div class="col-md-5">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name_last):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_last)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name_first):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_first)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gender):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gradeLevel):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gradeLevel)
            </dd>

        </dl>
    </div>
</div>

<br />

@using (Html.BeginForm("ClassAttendance", "Student", FormMethod.Post, new { id = "sectionform" }))
{
    <div class="row">
        <div class="col-md-4">
            @Html.Partial("_ClassAttendanceCalendar") @* configure grid in a partial view *@
        </div>
        <div class="col-md-8">
            <div id="schedule-content">
                <p class="muted">
                    
                </p>
            </div>
        </div>

    </div>

}

Schoology.App.Attendance/Views/Student/ClassIndex.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.User>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Students Attendance by Class";
}

<h3>@ViewBag.Title</h3>


@using (Html.BeginForm("ClassIndex", "Student", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

<script>

    $(function () {

        // Clear the search grid
        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row select event code
        //pageGrids.studentGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });

</script>

@Html.Grid(Model).Named("studentGrid").Columns(columns =>
{


    columns.Add(model => model.uid)
    .Titled("Id")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);

    columns.Add(model => model.position)
    .Titled("StudentID")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);

    /* Adding "OrderID" column: */
    columns.Add(model => model.name_last)
            .Titled("Last Name")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(150);

    columns.Add(model => model.name_first)
        .Titled("First Name")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(100);

    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(20)
    .RenderValueAs(d =>
        @<b>
            @Html.ActionLink("Attendance", "ClassAttendance", new { id = d.uid })

        </b>);

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(500)
        .RenderValueAs(d =>
            @<b>

            </b>);


}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Student/Course.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.User>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Attendance by Course";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Index", "Student", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

<script>

    $(function () {

        // Clear the search grid
        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row select event code
        //pageGrids.studentGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });

</script>

@Html.Grid(Model).Named("studentGrid").Columns(columns =>
{
    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(20)
        .RenderValueAs(d =>
            @<b>
                @Html.ActionLink("Attendance", "Attendance", new { id = d.uid })

            </b>);

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(20)
        .RenderValueAs(d =>
            @<b>
                @Html.ActionLink("Details", "Details", new { id = d.uid })

            </b>);

    columns.Add(model => model.uid)
    .Titled("Id")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);

    /* Adding "OrderID" column: */
    columns.Add(model => model.name_last)
            .Titled("Last Name")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(150);

    columns.Add(model => model.name_first)
        .Titled("First Name")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(150);

    columns.Add()
.Encoded(false)
.Sanitized(false)
.SetWidth(300)
.RenderValueAs(d =>
    @<b>

    </b>);





}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Student/Day.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.User>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Attendance by Day";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm("Index", "Student", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

<script>

    $(function () {

        // Clear the search grid
        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row select event code
        //pageGrids.studentGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });

</script>

@Html.Grid(Model).Named("studentGrid").Columns(columns =>
{
    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(20)
        .RenderValueAs(d =>
            @<b>
                @Html.ActionLink("Attendance", "Attendance", new { id = d.uid })

            </b>);

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(20)
        .RenderValueAs(d =>
            @<b>
                @Html.ActionLink("Details", "Details", new { id = d.uid })

            </b>);

    columns.Add(model => model.uid)
    .Titled("Id")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);

    /* Adding "OrderID" column: */
    columns.Add(model => model.name_last)
            .Titled("Last Name")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(150);

    columns.Add(model => model.name_first)
        .Titled("First Name")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(150);

    columns.Add()
.Encoded(false)
.Sanitized(false)
.SetWidth(300)
.RenderValueAs(d =>
    @<b>

    </b>);





}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Student/DayAttendance.cshtml
@model Schoology.Api.Entities.Models.User

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />

@{
    ViewBag.Title = "Student Attendance By Day";
}

<h3>@ViewBag.Title</h3>

<div class="row">
    <div class="col-md-1">
        <img height="84" width="100" src=@Model.picture_url />
    </div>

    <div  class="col-md-5">

        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.name_last):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_last)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name_first):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_first)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.gender):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.name_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name_title)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.gradeLevel):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.gradeLevel)
            </dd>

        </dl>
    </div>
</div>

<br />

@using (Html.BeginForm("DayAttendance", "Student", FormMethod.Post, new { id = "sectionform" }))
{
    <div class="row">
        <div class="col-md-4">
            @Html.Partial("_DayAttendanceCalendar") @* configure grid in a partial view *@
        </div>

        <div class="col-md-5">
            <div id="schedule-content">
                <p class="muted">
                    
                </p>
            </div>
        </div>

    </div>

}

Schoology.App.Attendance/Views/Student/DayIndex.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.User>
@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Students Attendance by Day";
}

<h3>@ViewBag.Title</h3>


@using (Html.BeginForm("DayIndex", "Student", FormMethod.Get))
{
    <div>
        Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
        <input id="Search" type="submit" value="Search" />
        <input id="Clear" type="submit" value="Clear" />
    </div>

}

<script>

    $(function () {

        // Clear the search grid
        $("#Clear").on("click", function (event) {
            $("#SearchString").val("");
        });

        // Grid row select event code
        //pageGrids.studentGrid.onRowSelect(function (e) {
        //    alert(e.row.uid);
        //});

    });

</script>

@Html.Grid(Model).Named("studentGrid").Columns(columns =>
{


    columns.Add(model => model.uid)
    .Titled("Id")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);

    columns.Add(model => model.position)
    .Titled("StudentID")
    .Filterable(false)
    .Sortable(false)
    .SetWidth(20);
    
    /* Adding "OrderID" column: */
    columns.Add(model => model.name_last)
            .Titled("Last Name")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(150);

    columns.Add(model => model.name_first)
        .Titled("First Name")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(100);

    columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(20)
    .RenderValueAs(d =>
        @<b>
            @Html.ActionLink("Attendance", "DayAttendance", new { id = d.uid })

        </b>);

    columns.Add()
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(500)
        .RenderValueAs(d =>
            @<b>

            </b>);


}).WithPaging(10).Selectable(false)