Schoology.App.Attendance/Controllers/CourseController.cs
using Newtonsoft.Json;
using Schoology.Api.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Schoology.Api.Entities.Models;
using System.Configuration;
using Schoology.App.Attendance.Models;
using System.Net;
using System.Security.Claims;
using RazorPDF;
using log4net;
using Schoology.Custom.Entities.Models;
using API_Library_2._0;


namespace Schoology.App.Attendance.Controllers
{
    public class CourseController : Controller
    {
        // Log file
        private static readonly ILog log = LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        private SchoologyDbContext db = new SchoologyDbContext();

        //private static List<GradingPeriod> _gradingPeriodList = new List<GradingPeriod>();
        //private static List<Course> _totalCourseList { get; set; }
        //private static List<Course> _filterCourseList { get; set; }

        [Authorize(Roles = "Admin, School Admin, Teacher, Front Desk")]
        /// <summary>
        /// Display the Courses and their sections. Sorting, Filtering, and Searching are provided. Plus navigation back to where last displayed.
        /// </summary>
        /// <param name="searchString">Find by Name SearchString to filter the Course Listing.</param>
        /// <returns></returns>
        public ActionResult Index(string searchString)
        {
            long uid = 0;

            List<Course> totalCourseList;
            List<Course> filterCourseList;

            // Create the list to hold the courses.
            List<Course> filterList = new List<Course>();

            // Initialize the Grid.MVC searching, sorting and search string.
            GridMVCModel gridMVCModel = new GridMVCModel();

            ViewBag.gridPage = 1;
            ViewBag.gridFilter = "";
            ViewBag.gridColumn = "";
            ViewBag.gridDir = 0;
            ViewBag.SearchString = "";

            // Proformance Issues
            // We only want to load data when we hit this page.
            // If the post-back for grid paging and filtering, do not reload the data.

            //KDC - Added
            totalCourseList = CourseService.Instance.GetCoursesWithSectionsJsonFile();
            filterCourseList = totalCourseList;

            // TODO: Make this easier to use
            // Get the current schoology user id.
            ClaimsIdentity identity = (ClaimsIdentity)User.Identity;
            List<Claim> claims = identity.Claims.ToList();
            var claimUid = claims.Where(c => c.Type == "http://www.schoology.com/uid").Select(c => c.Value).SingleOrDefault();
            uid = Convert.ToInt64(claimUid);

            // If this is a teacher, only get the courses the teacher teaches.
            if (User.IsInRole("Teacher"))
            {
                //log.ErrorFormat("[Course] - IsInRole(Teacher) - {0} - ID - {1}", User.Identity.Name, uid);

                // Only get the courses the teacher teaches
                //List<Course> teachersList = _totalCourseList.Where(x => x.section.Any(o => o.enrollments.Any(w => w.uid == uid))).ToList();
                List<Course> teachersList = totalCourseList.Where(x => x.section.Any(o => o.enrollments.Any(w => w.uid == uid))).ToList();

                // Now get only the sections the teacher teaches.
                foreach (Course course in teachersList)
                {
                    List<Section> sectionList = course.section.Where(x => x.enrollments.Any(e => e.uid == uid)).ToList();
                    course.section = sectionList;
                }

                //_totalCourseList = teachersList;
                totalCourseList = teachersList;
            }


            // If no query strings, load the data once and store in static variable.
            if (Request.QueryString.Count == 0)
            {
                // Get the course from Schoology json file.
                //_totalCourseList = CourseService.Instance.GetCoursesWithSectionsJsonFile();



                // Set the Grid.MVC grid-page to 1 because if we go to the details page and return it will reload all the data.
                ViewBag.gridPage = 1;

            }
            else
            {
                // Set the view bag variables to be passed to the details page so we can return back to where we started from.
                // Grid Page
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-page"]))
                {
                    ViewBag.gridPage = int.Parse(Request.QueryString["grid-page"]);
                }

                // Grid Filter
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-filter"]))
                {
                    ViewBag.gridFilter = Request.QueryString["grid-filter"];
                }

                // Grid Sort Direction
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-dir"]))
                {
                    ViewBag.gridDir = Request.QueryString["grid-dir"];
                }

                // Grid Sort Column
                if (!string.IsNullOrWhiteSpace(Request.QueryString["grid-column"]))
                {
                    ViewBag.gridColumn = Request.QueryString["grid-column"];
                }

                // Filter Textbox
                if (!string.IsNullOrWhiteSpace(Request.QueryString["SearchString"]))
                {
                    ViewBag.SearchString = Request.QueryString["SearchString"];
                }

            }

            // Filter the list by title, course code and section
            if (!string.IsNullOrEmpty(searchString))
            {
                ViewBag.SearchString = searchString;

                // Now that we have all the users, check to see if we need to filter them.
                if (!string.IsNullOrEmpty(searchString))
                {
                    //_filterCourseList = _totalCourseList.Where(s =>

                    //    s.title.ToLower().Contains(searchString.ToLower()) ||
                    //    s.course_code.ToLower().Contains(searchString.ToLower()) ||
                    //    s.section.Any(c => c.section_title.ToLower().Contains(searchString.ToLower()))
                        
                    //    ).ToList();

                    filterCourseList = totalCourseList.Where(s =>

                        s.title.ToLower().Contains(searchString.ToLower()) ||
                        s.course_code.ToLower().Contains(searchString.ToLower()) ||
                        s.section.Any(c => c.section_title.ToLower().Contains(searchString.ToLower()))

                        ).ToList();

                }
            }
            else
            {
                //_filterCourseList = _totalCourseList;
                filterCourseList = totalCourseList;
            }

            List<GetFacultyClassAttendanceTaken_Result> facultyAttendanceList;

            // DONT USE - SCHOOLOGY BUG WITH v1/users/me
            //User currentUser = UserService.Instance.GetCurrentUser();

            User currentUser = UserService.Instance.GetUser(uid);

            if (currentUser.school_uid == null)
            {
                facultyAttendanceList = db.GetFacultyClassAttendanceTaken().ToList();
            }
            else
            {
                facultyAttendanceList = db.GetFacultyClassAttendanceTakenById(Convert.ToInt32(currentUser.school_uid)).ToList();
            }

            foreach (Course course in filterCourseList)
            {
                foreach (Section section in course.section)
                {
                    foreach (GetFacultyClassAttendanceTaken_Result attendance in facultyAttendanceList)
                    {
                        if (Convert.ToInt32(section.section_code) == attendance.SectionCode)
                        {
                            section.attendanceTaken = "&nbsp;&nbsp;***Attendance Not Taken***";
                        }
                    }
                }
            }


            // Get the Parent's emails using the students EA7RecordsId
            //List<GetFacultyClassAttendanceTakenById> facultyList = db.GetFacultyClassAttendanceTakenById(Convert.ToInt32(currentUser.school_uid)).ToList();

            //List<GetFacultyClassAttendanceTaken_Result> facultyList = db.GetFacultyClassAttendanceTakenById(Convert.ToInt32(2591)).ToList();

            //List<GetFacultyClassAttendanceTaken_Result> facultyList = db.GetFacultyClassAttendanceTaken().ToList();

            gridMVCModel.GridPage = Convert.ToInt32(ViewBag.gridPage);
            gridMVCModel.GridFilter = ViewBag.gridFilter;
            gridMVCModel.GridColumn = ViewBag.gridColumn;
            gridMVCModel.GridDir = Convert.ToInt32(ViewBag.gridDir);
            gridMVCModel.SearchString = ViewBag.searchString;

            Session["gridMVCModel"] = gridMVCModel;

            //return View(_filterCourseList);
            return View(filterCourseList);
        }


        /// <summary>
        /// The Section view for each student in the Course Section
        /// </summary>
        /// <param name="id">Section Id.</param>
        /// <param name="currentDate">Current Date selected from the JQuery Datepicker.</param>
        /// <returns></returns>
        [Authorize(Roles = "Admin, School Admin, Teacher, Front Desk")]
        public ActionResult Section(long id, DateTime currentDate)
        {

            List<Course> totalCourseList;

            totalCourseList = CourseService.Instance.GetCoursesWithSectionsJsonFile();

            SetGridMVCViewBag();

            // This is to check if the section meets certian business rules. See the DebugController and view. It is enable there.
            // This is commentted out becuase of performance reasons. 
            //string sectionValidationSummary = SectionService.Instance.ValidateSection(id);
            //if (!string.IsNullOrEmpty(sectionValidationSummary))

Schoology.App.Attendance/Views/Course/Index.cshtml
@model IEnumerable<Schoology.Api.Entities.Models.Course>

@using GridMvc.Html
@using GridMvc.Sorting

@{
    ViewBag.Title = "Attendance by Course";
}

<h3>@ViewBag.Title</h3>


    <meta name="viewport" content="width=device-width" />

    <script>

        $(function () {

            $("#Clear").on("click", function (event) {
                $("#SearchString").val("");
            });

            // Grid row selected event
            //pageGrids.courseGrid.onRowSelect(function (e) {
            //    alert(e.row.uid);
            //});

        });

    </script>


    @using (Html.BeginForm("Index", "Course", FormMethod.Get))
    {
        @*<p>
            Select Grading Period: @Html.DropDownList("gradingPeriod")
            <input type="submit" value="Filter" />
        </p>*@

        <div>
            Find by name: @Html.TextBox("SearchString", ViewBag.SearchString as string)
            <input id="Search" type="submit" value="Search" />
            <input id="Clear" type="submit" value="Clear" />
        </div>

    }

@Html.Grid(Model).Named("courseGrid").Columns(columns =>
{


    /* Adding "OrderID" column: */
    columns.Add(model => model.title)
            .Titled("Title")
            .Filterable(true)
            .Sortable(true)
            .SortInitialDirection(GridSortDirection.Ascending)
            .SetWidth(200);

    columns.Add(model => model.course_code)
        .Titled("Course Code")
        .Filterable(true)
        .Sortable(true)
        .SetWidth(30);

    columns.Add()
        .Titled("Sections")
        .Encoded(false)
        .Sanitized(false)
        .SetWidth(200)
        .RenderValueAs(d =>
            @<b>
                 @foreach (var a in d.section)
                 {

                     

                        @*@Html.ActionLink(@a.section_title, "Index", new RouteValueDictionary(
                            new { controller = "Section", id = a.id }))*@

                    @Html.ActionLink(@a.section_title + System.Net.WebUtility.HtmlDecode(@a.attendanceTaken), "Section", new { id = a.id, currentDate = DateTime.Now })
                     

                     <br />
                 }

            </b>

        );



    @*columns.Add()
    .Encoded(false)
    .Sanitized(false)
    .SetWidth(100)
    .RenderValueAs(d =>
        @<b>

        </b>);*@


}).WithPaging(10).Selectable(false)

Schoology.App.Attendance/Views/Course/RosterPDF.cshtml
@model Schoology.Api.Entities.Models.Section
@{
    Layout = null;
}


@{
    ViewBag.Title = "Class Roster";
}

<style>

table {
    border-collapse: separate;
    border-spacing: 0 5em;

}

</style>


<center>
    <h2>Valor Christian High School</h2>


    <h3>Class Roster</h3>
</center>

<table >
    <tr>
        <td align="right">Date:&nbsp;</td>
        <td>@ViewBag.Date</td>
    </tr>
    <tr>
        <td align="right">Course Title:&nbsp;</td>
        <td>@Model.course_title</td>
    </tr>
    <tr>
        <td align="right">Course Code:&nbsp;</td>
        <td>@Model.course_code</td>
    </tr>
    <tr>
        <td align="right">Section Title:&nbsp;</td>
        <td>@Model.section_title</td>
    </tr>
    <tr>
        @if (Model.teachers.Count > 0) { 
        <td align="right">Faculty:&nbsp;</td>

            for (int i = 0; i <= Model.teachers.Count - 1; i++)
            {
                
                <td>@Model.teachers[i].name_display<p></p></td>
                
            }

        }
        else
        {
            <td align="right">Faculty:&nbsp;</td>
            <td>n/a</td>
        }
    </tr>
</table>

<br />
<hr />

    <table id='myTable' class="table" align="center">
     
            <tr>
                <th>@Html.CheckBox("checkall")</th>
                <th>Student Name</th>
            </tr>

            <tbody>

                @for (int i = 0; i < Model.enrollments.Count; ++i)
                {
                    <tr>
                        <td align="right">
                            ________
                        </td>
                        <td>
                            @Html.DisplayFor(m => m.enrollments[i].name_last), @Html.DisplayFor(m => m.enrollments[i].name_first)


                        </td>


                    </tr>

                }


            </tbody>
      
</table>
 

Schoology.App.Attendance/Views/Course/Section.cshtml
@model Schoology.Api.Entities.Models.Section

<script src="~/Scripts/jquery.blockUI.js" type="text/javascript"></script>
<link rel="Stylesheet" href="~/Content/themes/redmond/jquery-ui.css" />
@*<link rel="Stylesheet" href="~/Content/themes/BILTZER/jquery-ui.css" />*@

@{
    ViewBag.Title = "Attendance by Course Section";
}

<h3>@ViewBag.Title</h3>

<div class="row">

    <div id="sectioninfo" class="col-md-3">

        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.course_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.course_code):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.course_code)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.section_title):
            </dt>

            <dd>
                @Html.DisplayFor(model => model.section_title)
            </dd>

            <dt>
                Faculty:
            </dt>

            <dd>
                @if (Model.teachers.Count > 0)
                {
                    for (int i = 0; i <= Model.teachers.Count - 1; i++)
                    {
                        @Html.DisplayFor(model => model.teachers[i].name_display) <br />
                    }
 
                }
                else
                {
                    <p>n/a</p>
                }
            </dd>


        </dl>
    </div>

    <p>
        <b>
            @Html.ActionLink("Print Roster", "RosterPDF", "Course", new { id = @Model.id, date = @ViewBag.searchDate }, new { target = "_blank" })
        </b>
    </p>

</div>

<p>
    @Html.ActionLink("Back to List", "Index",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })


</p>

 


@using (Html.BeginForm("Section", "Course", FormMethod.Post, new { id = "sectionform" }))
{ 
    
<div class="editor-field" >
    <label for="date">Attendance Date:</label>

    @Html.TextBox("attendancedate")

</div>

<br />


    <label>Apply to checked students:&nbsp;&nbsp;</label>@Html.DropDownList("SelectAllAttendanceCodes",

        new SelectList(ViewBag.AttendanceCode, "Key", "Value"),

                                    // Text for the first 'default' option
                                    "- Select Attendance Code -"

                                    )


<label>&nbsp;&nbsp;Comment:</label> @Html.TextBox("SelectAllComment", "", new { style="width:500px"})
<br />
<br />
    
<table id='myTable' class="table">
  
    <tr>
        <th>@Html.CheckBox("checkall")</th>
        <th>Student Name</th>
        <th>Attendance Code</th>
        <th>Comment</th>
    </tr>

    <tbody>

        @for (int i = 0; i < Model.enrollments.Count; ++i)
        {
            <tr>
                <td>
                    <input type="checkbox" name="sid" value="@Model.enrollments[i].attendances[0].enrollment_id" class="sid" />
                </td>
                <td>
                    <img height="42" width="50" src=@Model.enrollments[i].picture_url /> @Html.DisplayFor(m => m.enrollments[i].name_last), @Html.DisplayFor(m => m.enrollments[i].name_first) <a href=@Html.Raw(@String.Format(@"'https://www.schoology.com/course/{0}/reports/{1}/attendance'", Model.id, Model.enrollments[i].uid)) target="_blank"><img src="~/Images/stats.png" align="top" /></a>
                    @Html.HiddenFor(m => Model.enrollments[i].attendances[0].enrollment_id)
                    @Html.HiddenFor(m => Model.enrollments[i].attendances[0].date)

                </td>

                <td>
                    @*@Html.CheckBox("checkbox_" + @Model.enrollments[i].attendances[0].enrollment_id)*@

                    @Html.HiddenFor(m => @Model.enrollments[i].id)
                    @Html.HiddenFor(m => @Model.enrollments[i].name_first)
                    @Html.HiddenFor(m => @Model.enrollments[i].name_last)

                    @Html.DropDownListFor(m => Model.enrollments[i].attendances[0].status,

                        new SelectList(ViewBag.AttendanceCode, "Key", "Value", Model.enrollments[i].attendances[0].status),



                                            // A class name to put on the "<select>"
                                        new Dictionary<string, object> { { "data-val", false } }
                                            )
                </td>

                <td>

                    @Html.TextBoxFor(m => m.enrollments[i].attendances[0].comment)
                    @*@Html.EditorFor(m => m.enrollments[i].attendances[0].comment)*@

                </td>
            </tr>

        }

        </tbody>

</table>

    <div class="form-group">
        @*<div class="col-md-offset-2 col-md-10">*@
            <div>
                <input type="submit" value="Save Changes"  id="save" />
            </div>
    </div>
}

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.uid }) |*@
    @Html.ActionLink("Back to List", "Index",
        new RouteValueDictionary {
                                    { "grid-page", @ViewBag.gridPage },
                                    { "grid-filter", @ViewBag.gridFilter },
                                    { "grid-column", @ViewBag.gridColumn },
                                    { "grid-dir", @ViewBag.gridDir },
                                    { "SearchString", @ViewBag.SearchString }
                                 })

</p>

<script type="text/javascript">

    // unblock when ajax activity stops 
    $(document).ajaxStop($.unblockUI);

    $(function () {


        // 0 = sunday, 1 = monday, 2 = tuesday, 3 = wednesday, 4 = thrusday, 5 = friday, 6 = saturday
        var daysToDisable = [0, 6];

        // This way does not include modified days. So we are going to disable it.
        //var daysToDisable = JSON.parse("[" + '@ViewBag.daysToDisable' + "]");

        $('#attendancedate').datepicker({
            maxDate: 0,
            changeYear: true,
            yearRange: '+0:+1',
            dateFormat: "yy-mm-dd",
            changeMonth: true,
            changeYear: true,
            showOn: 'both',
            buttonImage: "../../images/attendance.png",
            buttonImageOnly: true,
            autoSize: true,
            onSelect: function (dateText, inst) {

                //$.blockUI({ message: $('#domMessage') });
                window.location = '@Url.Action("section")?currentDate=' + dateText;
                //$.unblockUI();
            },

            beforeShowDay: disableSpecificWeekDays

        }).datepicker("setDate", '@ViewBag.searchDate');

        function disableSpecificWeekDays(date) {
            var day = date.getDay();
            for (i = 0; i < daysToDisable.length; i++) {
                if ($.inArray(day, daysToDisable) != -1) {
                    return [false];
                }
            }
            return [true];
        }

        // Fires the onSelect event when page loads.
        $('.ui-datepicker-current-day').click

        //$('#save').click(function () {
        //    $.blockUI({ message: '<h1><img src="../../images/busy.gif" /> Saving Data...</h1>' });
        //});

        $('#save').click(function () {

            var ischeckallChecked = $('#checkall').is(":checked")
            if (ischeckallChecked) {
                if ($('#SelectAllAttendanceCodes').val() == false) {
                    //alert("Please select an attendance code.");
                    //$.blockUI({ message: '<h1>Attendance Code is required.</h1>' });
                    ValidationDialog("Attendance Code is required.");
                    //$("#dialog").dialog("open");
                    return false; // will not refresh the page.
                }
            }

            var ischeckallChecked = $('#checkall').is(":checked")
            if ($('#SelectAllAttendanceCodes').val() != false && !ischeckallChecked) {
                    ValidationDialog("At least one student must be checked.");
                    return false; // will not refresh the page.    
            }

            $.blockUI({
                message: '<h4>Please Wait...</h4>',

                css: {
                    border: 'none',
                    padding: '15px',
                    backgroundColor: '#000',
                    '-webkit-border-radius': '10px',
                    '-moz-border-radius': '10px',
                    opacity: .5,
                    color: '#fff'
                }
            });




        });


        function ValidationDialog(message) {
            $("#dialog").html(message);

            // Define the Dialog and its properties.
            $("#dialog").dialog({
                resizable: false,
                modal: true,
                title: "Attendance by Course Section",
                height: 150,
                width: 300
            });
        }


    });

</script>

<script>
    $("document").ready(function () {

        $('#myTable td input:checkbox').prop('disabled', true);

        $('#myTable th input:checkbox').click(
            function () {
                $('input:checkbox').prop('checked', this.checked);
            }
        );

        $('#myTable tr input:checkbox').click(
            function () {
                var checkedCount = $('#myTable td input:checkbox:checked').length;
                //alert(checkedCount);
                var totalCount = $('#myTable td input:checkbox').length;
                //alert(totalCount);
                var selectAllChecked = $('#myTable th input:checkbox').prop('checked')
                //alert(selectAllChecked);



                $('#myTable th input:checkbox').prop('checked', selectAllChecked && checkedCount > 0);
                $('#myTable td input:checkbox').prop('disabled', !selectAllChecked);

                if (!selectAllChecked) {
                    $('#myTable th input:checkbox').focus();
                    $('#myTable td input:checkbox').prop('checked', false);

                }

            }
        );


    });
</script>

<div id="dialog">

</div>